### ISSUE TITLE
Add missing fields in package.json (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/community-client#5]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)
- [Community](https://github.com/DAVFoundation/community/labels/first-timers-only)
- [community-client](https://github.com/DAVFoundation/community-client/labels/first-timers-only)
- [website](https://github.com/DAVFoundation/website/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Community-Client

The DAV project you are looking at is Community-Client. It is the frontend for DAV's community site, which you can see at https://my.dav.network/

### The Issue

The package.json file is missing some required fields. Your task for this issue is...

- [ ] Add `DAV community site frontend` as description.
- [ ] Add the `repository` field as mentioned [here](https://docs.npmjs.com/files/package.json#repository)

### Contributing to Community-Client

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Community-Client GitHub page](https://github.com/DAVFoundation/community-client).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/community-client.git`
- [ ] **Make changes in the package.json file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/community-client](https://github.com/YOUR-USER-NAME/community-client)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by jj-owens** [comment]
Hello, may I work on this for you?

**Comment by TalAter** [comment]
Of course. Thank you so much!

**Comment by cg-cnu** [comment]
Thanks for your contribution 💯  👏
